import ROOT
from ROOT import gROOT
from ROOT import gStyle
from ROOT import TF1
from ROOT import kRed 
ROOT.gROOT.SetBatch(True)  # go into batch mode, stop trying to actively popup graphics on the screen
from subprocess import call
import string, re
from array import array
import sys

inputname = "EffStudy.root"
inputfile = ROOT.TFile.Open( inputname )

#gStyle.SetStatX(0.92)
#gStyle.SetStatY(0.92)
#gStyle.SetOptStat("emr")
#gStyle.SetOptFit(1111)



h_cutflow = inputfile.Get("cutflow")
#h_trk_eta = inputfile.Get("trk_eta_org")
h_trk_eta = inputfile.Get("trk_eta")
h_trk_P = inputfile.Get("trk_P")
h_trk_phi = inputfile.Get("trk_phi")
h_trk_sec = inputfile.Get("trk_sec")
#h_hit_channel_org = inputfile.Get("hit_channel_org")
h_hit_channel = inputfile.Get("hit_channel")
h2_trk_sec_phi = inputfile.Get("trk_sec_phi")
h2_trk_P_eta_0 = inputfile.Get("trk_P_eta_0")
h2_trk_P_phi_0 = inputfile.Get("trk_P_phi_0")
h2_trk_eta_phi_0 = inputfile.Get("trk_eta_phi_0")
h2_trk_P_eta_1 = inputfile.Get("trk_P_eta_1")
h2_trk_P_phi_1 = inputfile.Get("trk_P_phi_1")
h2_trk_eta_phi_1 = inputfile.Get("trk_eta_phi_1")
h_overlap = inputfile.Get("overlap")
h_eff_phi = inputfile.Get("eff_phi")
h_eff_eta = inputfile.Get("eff_eta")
h2_eff_channel = inputfile.Get("eff_channel")

h_eff_phi_noStuck = inputfile.Get("eff_phi_noStuck")
h_eff_eta_noStuck = inputfile.Get("eff_eta_noStuck")

h2_eff_channel_onlyNumerator = inputfile.Get("eff_channel_numerator")

for i in range(-16,17):
	for j in range(1,5):
		myhist = inputfile.Get("qsum_sector_%d_layer_%d" % (i, j))
		if myhist == None: continue
		myc= ROOT.TCanvas("myc", "myc", 800, 600)
		myc.SetMargin(0.15,0.075,0.15,0.075)
		myhist.SetStats(ROOT.kFALSE)
		myhist.SetTitle("sector %d, layer %d" % (i, j))
		myhist.GetYaxis().SetTitle("Events")
		myhist.GetYaxis().SetTitleOffset(1.4)
		myhist.GetYaxis().SetTitleSize(0.04)
		myhist.GetXaxis().SetTitle("qsum")
		myhist.Draw()
#        fit_x = TF1("fit_x", "landau", 0., 10000000.)
#		fit_x = TF1("fit_x", "landau", 0., 5000000.)
#		fit_x.SetLineColor(kRed)
#		myhist.Fit("fit_x")
		myc.Update()
		myc.SaveAs("effplots/qsum_sector_%d_layer_%d.eps" % (i,j))
		myc.SaveAs("effplots/qsum_sector_%d_layer_%d.png" % (i,j))
		myc.Close()


myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_cutflow.SetStats(ROOT.kFALSE)
h_cutflow.SetTitle("")
h_cutflow.SetMaximum(1.e7)
h_cutflow.GetXaxis().SetTitle("Cutflow")
h_cutflow.GetXaxis().SetNdivisions(103)
h_cutflow.GetYaxis().SetTitle("Events")
h_cutflow.GetYaxis().SetTitleOffset(1.4)
h_cutflow.GetYaxis().SetTitleSize(0.04)
h_cutflow.Draw()
myc.Update()
myc.SaveAs("effplots/cutflow.eps")
myc.SaveAs("effplots/cutflow.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_trk_eta.SetStats(ROOT.kFALSE)
h_trk_eta.SetTitle("")
h_trk_eta.GetXaxis().SetTitle("Track eta")
h_trk_eta.GetYaxis().SetTitle("Number of tracks")
h_trk_eta.GetYaxis().SetTitleOffset(1.4)
h_trk_eta.GetYaxis().SetTitleSize(0.04)
h_trk_eta.Draw()
myc.Update()
myc.SaveAs("effplots/h_trk_eta.eps")
myc.SaveAs("effplots/h_trk_eta.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_trk_P.SetStats(ROOT.kFALSE)
h_trk_P.SetTitle("")
h_trk_P.GetXaxis().SetTitle("Track P [GeV]")
h_trk_P.GetYaxis().SetTitle("Number of tracks")
h_trk_P.GetYaxis().SetTitleOffset(1.4)
h_trk_P.GetYaxis().SetTitleSize(0.04)
h_trk_P.Draw()
myc.Update()
myc.SaveAs("effplots/h_trk_P.eps")
myc.SaveAs("effplots/h_trk_P.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_trk_phi.SetStats(ROOT.kFALSE)
h_trk_phi.SetTitle("")
h_trk_phi.GetXaxis().SetTitle("Track phi")
h_trk_phi.GetYaxis().SetTitle("Number of tracks")
h_trk_phi.GetYaxis().SetTitleOffset(1.4)
h_trk_phi.GetYaxis().SetTitleSize(0.04)
h_trk_phi.Draw("HIST")
myc.Update()
error_trk_phi = ROOT.TGraphAsymmErrors(h_trk_phi)
error_trk_phi.SetFillStyle(3001)
error_trk_phi.SetFillColor(ROOT.kRed-4)
error_trk_phi.Draw("2 SAME")
myc.Update()
myc.SaveAs("effplots/h_trk_phi.eps")
myc.SaveAs("effplots/h_trk_phi.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_trk_sec.SetStats(ROOT.kFALSE)
h_trk_sec.SetTitle("")
h_trk_sec.GetXaxis().SetTitle("Sector number")
h_trk_sec.GetYaxis().SetTitle("Number of tracks")
h_trk_sec.GetYaxis().SetTitleOffset(1.4)
h_trk_sec.GetYaxis().SetTitleSize(0.04)
h_trk_sec.Draw("HIST")
myc.Update()
error_trk_sec = ROOT.TGraphAsymmErrors(h_trk_sec)
error_trk_sec.SetFillStyle(3001)
error_trk_sec.SetFillColor(ROOT.kRed-4)
error_trk_sec.Draw("2 SAME")
myc.Update()
myc.SaveAs("effplots/h_trk_sec.eps")
myc.SaveAs("effplots/h_trk_sec.png")
myc.Close()

'''
myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_hit_channel_org.SetStats(ROOT.kFALSE)
h_hit_channel_org.SetTitle("")
h_hit_channel_org.GetXaxis().SetTitle("Channel number")
h_hit_channel_org.GetYaxis().SetTitle("Number of hits")
h_hit_channel_org.GetYaxis().SetTitleOffset(1.4)
h_hit_channel_org.GetYaxis().SetTitleSize(0.04)
h_hit_channel_org.Draw()
myc.Update()
myc.SaveAs("effplots/h_hit_channel_org.eps")
myc.SaveAs("effplots/h_hit_channel_org.png")
myc.Close()
'''

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_hit_channel.SetStats(ROOT.kFALSE)
h_hit_channel.SetTitle("")
h_hit_channel.GetXaxis().SetTitle("Channel number")
h_hit_channel.GetYaxis().SetTitle("Number of hits")
h_hit_channel.GetYaxis().SetTitleOffset(1.4)
h_hit_channel.GetYaxis().SetTitleSize(0.04)
h_hit_channel.Draw()
myc.Update()
myc.SaveAs("effplots/h_hit_channel.eps")
myc.SaveAs("effplots/h_hit_channel.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_sec_phi.SetMaximum(50000.)
h2_trk_sec_phi.SetStats(ROOT.kFALSE)
h2_trk_sec_phi.SetTitle("")
h2_trk_sec_phi.GetXaxis().SetTitle("Sector number")
h2_trk_sec_phi.GetYaxis().SetTitle("Track phi")
h2_trk_sec_phi.GetYaxis().SetTitleOffset(0.9)
h2_trk_sec_phi.GetYaxis().SetTitleSize(0.04)
h2_trk_sec_phi.GetZaxis().SetTitle("Events")
h2_trk_sec_phi.GetZaxis().SetTitleOffset(1.3)
h2_trk_sec_phi.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_trk_sec_phi.eps")
myc.SaveAs("effplots/h2_trk_sec_phi.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_sec_phi.SetMaximum(50000.)
h2_trk_sec_phi.SetStats(ROOT.kFALSE)
h2_trk_sec_phi.SetTitle("")
h2_trk_sec_phi.GetXaxis().SetTitle("Sector number")
h2_trk_sec_phi.GetYaxis().SetTitle("Track phi")
h2_trk_sec_phi.GetYaxis().SetTitleOffset(0.9)
h2_trk_sec_phi.GetYaxis().SetTitleSize(0.04)
h2_trk_sec_phi.GetZaxis().SetTitle("Events")
h2_trk_sec_phi.Draw("")
myc.Update()
myc.SaveAs("effplots/h2_trk_sec_phi_2.eps")
myc.SaveAs("effplots/h2_trk_sec_phi_2.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_P_eta_0.SetMaximum(50000.)
h2_trk_P_eta_0.SetStats(ROOT.kFALSE)
h2_trk_P_eta_0.SetTitle("")
h2_trk_P_eta_0.GetXaxis().SetTitle("Track P [GeV]")
h2_trk_P_eta_0.GetYaxis().SetTitle("Track eta")
h2_trk_P_eta_0.GetYaxis().SetTitleOffset(0.9)
h2_trk_P_eta_0.GetYaxis().SetTitleSize(0.04)
h2_trk_P_eta_0.GetZaxis().SetTitle("Events")
h2_trk_P_eta_0.GetZaxis().SetTitleOffset(1.3)
h2_trk_P_eta_0.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_trk_P_eta_0.eps")
myc.SaveAs("effplots/h2_trk_P_eta_0.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_P_phi_0.SetMaximum(50000.)
h2_trk_P_phi_0.SetStats(ROOT.kFALSE)
h2_trk_P_phi_0.SetTitle("")
h2_trk_P_phi_0.GetXaxis().SetTitle("Track P [GeV]")
h2_trk_P_phi_0.GetYaxis().SetTitle("Track phi")
h2_trk_P_phi_0.GetYaxis().SetTitleOffset(0.9)
h2_trk_P_phi_0.GetYaxis().SetTitleSize(0.04)
h2_trk_P_phi_0.GetZaxis().SetTitle("Events")
h2_trk_P_phi_0.GetZaxis().SetTitleOffset(1.3)
h2_trk_P_phi_0.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_trk_P_phi_0.eps")
myc.SaveAs("effplots/h2_trk_P_phi_0.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_eta_phi_0.SetMaximum(50000.)
h2_trk_eta_phi_0.SetStats(ROOT.kFALSE)
h2_trk_eta_phi_0.SetTitle("")
h2_trk_eta_phi_0.GetXaxis().SetTitle("Track eta")
h2_trk_eta_phi_0.GetYaxis().SetTitle("Track phi")
h2_trk_eta_phi_0.GetYaxis().SetTitleOffset(0.9)
h2_trk_eta_phi_0.GetYaxis().SetTitleSize(0.04)
h2_trk_eta_phi_0.GetZaxis().SetTitle("Events")
h2_trk_eta_phi_0.GetZaxis().SetTitleOffset(1.3)
h2_trk_eta_phi_0.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_trk_eta_phi_0.eps")
myc.SaveAs("effplots/h2_trk_eta_phi_0.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_P_eta_1.SetMaximum(50000.)
h2_trk_P_eta_1.SetStats(ROOT.kFALSE)
h2_trk_P_eta_1.SetTitle("")
h2_trk_P_eta_1.GetXaxis().SetTitle("Track P [GeV]")
h2_trk_P_eta_1.GetYaxis().SetTitle("Track eta")
h2_trk_P_eta_1.GetYaxis().SetTitleOffset(0.9)
h2_trk_P_eta_1.GetYaxis().SetTitleSize(0.04)
h2_trk_P_eta_1.GetZaxis().SetTitle("Events")
h2_trk_P_eta_1.GetZaxis().SetTitleOffset(1.3)
h2_trk_P_eta_1.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_trk_P_eta_1.eps")
myc.SaveAs("effplots/h2_trk_P_eta_1.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_P_phi_1.SetMaximum(50000.)
h2_trk_P_phi_1.SetStats(ROOT.kFALSE)
h2_trk_P_phi_1.SetTitle("")
h2_trk_P_phi_1.GetXaxis().SetTitle("Track P [GeV]")
h2_trk_P_phi_1.GetYaxis().SetTitle("Track phi")
h2_trk_P_phi_1.GetYaxis().SetTitleOffset(0.9)
h2_trk_P_phi_1.GetYaxis().SetTitleSize(0.04)
h2_trk_P_phi_1.GetZaxis().SetTitle("Events")
h2_trk_P_phi_1.GetZaxis().SetTitleOffset(1.3)
h2_trk_P_phi_1.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_trk_P_phi_1.eps")
myc.SaveAs("effplots/h2_trk_P_phi_1.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.08,0.14,0.1,0.05)
#ROOT.gPad.SetLogz(1)
#h2_trk_eta_phi_1.SetMaximum(50000.)
h2_trk_eta_phi_1.SetStats(ROOT.kFALSE)
h2_trk_eta_phi_1.SetTitle("")
h2_trk_eta_phi_1.GetXaxis().SetTitle("Track eta")
h2_trk_eta_phi_1.GetYaxis().SetTitle("Track phi")
h2_trk_eta_phi_1.GetYaxis().SetTitleOffset(0.9)
h2_trk_eta_phi_1.GetYaxis().SetTitleSize(0.04)
h2_trk_eta_phi_1.GetZaxis().SetTitle("Events")
h2_trk_eta_phi_1.GetZaxis().SetTitleOffset(1.3)
h2_trk_eta_phi_1.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_trk_eta_phi_1.eps")
myc.SaveAs("effplots/h2_trk_eta_phi_1.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 1200, 600)
myc.SetMargin(0.06,0.03,0.1,0.05)
h_eff_phi.SetStats(ROOT.kFALSE)
h_eff_phi.SetTitle("")
h_eff_phi.SetMaximum(1.)
h_eff_phi.SetFillColor(ROOT.kRed-9)
h_eff_phi.SetLineColor(ROOT.kRed+2)
h_eff_phi.GetXaxis().SetTitle("Sector number")
h_eff_phi.GetXaxis().SetNdivisions(134)
h_eff_phi.GetYaxis().SetTitle("Phi Efficiency")
h_eff_phi.GetYaxis().SetTitleOffset(0.7)
h_eff_phi.GetYaxis().SetTitleSize(0.04)
h_eff_phi.Draw("HIST")
myc.Update()
error_eff_phi = ROOT.TGraphAsymmErrors(h_eff_phi)
error_eff_phi.SetFillStyle(3001)
error_eff_phi.SetFillColor(ROOT.kRed+2)
error_eff_phi.Draw("2 SAME")
myc.Update()
myc.SaveAs("effplots/h_eff_phi.eps")
myc.SaveAs("effplots/h_eff_phi.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 1200, 600)
myc.SetMargin(0.06,0.03,0.1,0.05)
h_eff_phi_noStuck.SetStats(ROOT.kFALSE)
h_eff_phi_noStuck.SetTitle("")
h_eff_phi_noStuck.SetMaximum(1.)
h_eff_phi_noStuck.SetFillColor(ROOT.kRed-9)
h_eff_phi_noStuck.SetLineColor(ROOT.kRed+2)
h_eff_phi_noStuck.GetXaxis().SetTitle("Sector number")
h_eff_phi_noStuck.GetXaxis().SetNdivisions(134)
h_eff_phi_noStuck.GetYaxis().SetTitle("Phi Efficiency")
h_eff_phi_noStuck.GetYaxis().SetTitleOffset(0.7)
h_eff_phi_noStuck.GetYaxis().SetTitleSize(0.04)
h_eff_phi_noStuck.Draw("HIST")
myc.Update()
error_eff_phi_noStuck = ROOT.TGraphAsymmErrors(h_eff_phi_noStuck)
error_eff_phi_noStuck.SetFillStyle(3001)
error_eff_phi_noStuck.SetFillColor(ROOT.kRed+2)
error_eff_phi_noStuck.Draw("2 SAME")
myc.Update()
myc.SaveAs("effplots/h_eff_phi_noStuck.eps")
myc.SaveAs("effplots/h_eff_phi_noStuck.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 1200, 600)
myc.SetMargin(0.06,0.03,0.1,0.05)
h_eff_eta.SetStats(ROOT.kFALSE)
h_eff_eta.SetTitle("")
h_eff_eta.SetMaximum(1.)
h_eff_eta.SetFillColor(ROOT.kRed-9)
h_eff_eta.SetLineColor(ROOT.kRed+2)
h_eff_eta.GetXaxis().SetTitle("Sector number")
h_eff_eta.GetXaxis().SetNdivisions(134)
h_eff_eta.GetYaxis().SetTitle("Eta Efficiency")
h_eff_eta.GetYaxis().SetTitleOffset(0.7)
h_eff_eta.GetYaxis().SetTitleSize(0.04)
h_eff_eta.Draw("HIST")
myc.Update()
error_eff_eta = ROOT.TGraphAsymmErrors(h_eff_eta)
error_eff_eta.SetFillStyle(3001)
error_eff_eta.SetFillColor(ROOT.kRed+2)
error_eff_eta.Draw("2 SAME")
myc.Update()
myc.SaveAs("effplots/h_eff_eta.eps")
myc.SaveAs("effplots/h_eff_eta.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 1200, 600)
myc.SetMargin(0.06,0.03,0.1,0.05)
h_eff_eta_noStuck.SetStats(ROOT.kFALSE)
h_eff_eta_noStuck.SetTitle("")
h_eff_eta_noStuck.SetMaximum(1.)
h_eff_eta_noStuck.SetFillColor(ROOT.kRed-9)
h_eff_eta_noStuck.SetLineColor(ROOT.kRed+2)
h_eff_eta_noStuck.GetXaxis().SetTitle("Sector number")
h_eff_eta_noStuck.GetXaxis().SetNdivisions(134)
h_eff_eta_noStuck.GetYaxis().SetTitle("Eta Efficiency")
h_eff_eta_noStuck.GetYaxis().SetTitleOffset(0.7)
h_eff_eta_noStuck.GetYaxis().SetTitleSize(0.04)
h_eff_eta_noStuck.Draw("HIST")
myc.Update()
error_eff_eta_noStuck = ROOT.TGraphAsymmErrors(h_eff_eta_noStuck)
error_eff_eta_noStuck.SetFillStyle(3001)
error_eff_eta_noStuck.SetFillColor(ROOT.kRed+2)
error_eff_eta_noStuck.Draw("2 SAME")
myc.Update()
myc.SaveAs("effplots/h_eff_eta_noStuck.eps")
myc.SaveAs("effplots/h_eff_eta_noStuck.png")
myc.Close()

# set the palette to make range close to 1 more sensitive
NRGBs = 7
NCont = 100
stops = [0, 0.3, 0.6, 0.8, 0.95, 0.98 ,1]
#stops = [0, 0.17, 0.34, 0.51, 0.68, 0.85 ,1]
Red =   [0.6, 0.1, 0.0, 0.0, 1.0, 1.0, 1.0]
Green = [0.0, 0.5, 0.9, 0.9, 1.0, 0.5, 0.0]
Blue =  [0.8, 0.8, 0.9, 0.3, 0.0, 0.0, 0.0]
stopsArray = array('d', stops)
redArray   = array('d', Red)
greenArray = array('d', Green)
blueArray  = array('d', Blue)
ROOT.TColor.CreateGradientColorTable(NRGBs, stopsArray, redArray, greenArray, blueArray, NCont)
gStyle.SetNumberContours(NCont)

myc= ROOT.TCanvas("myc", "myc", 1000, 800)
myc.SetMargin(0.08,0.15,0.1,0.03)
#ROOT.gPad.SetLogz(1)
#h2_eff_channel.SetMaximum(1300.)
h2_eff_channel.SetStats(ROOT.kFALSE)
h2_eff_channel.SetTitle("")
h2_eff_channel.GetXaxis().SetTitle("Channel number [GeV]")
h2_eff_channel.GetYaxis().SetTitle("Sector number")
h2_eff_channel.GetYaxis().SetTitleOffset(0.9)
h2_eff_channel.GetYaxis().SetTitleSize(0.04)
h2_eff_channel.GetZaxis().SetTitle("Hits")
h2_eff_channel.GetZaxis().SetTitleOffset(1.3)
h2_eff_channel.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_eff_channel.eps")
myc.SaveAs("effplots/h2_eff_channel.png")
myc.Close()

myc= ROOT.TCanvas("myc", "myc", 1000, 800)
myc.SetMargin(0.08,0.15,0.1,0.03)
h2_eff_channel_onlyNumerator.SetStats(ROOT.kFALSE)
h2_eff_channel_onlyNumerator.SetTitle("")
h2_eff_channel_onlyNumerator.GetXaxis().SetTitle("Channel number [GeV]")
h2_eff_channel_onlyNumerator.GetYaxis().SetTitle("Sector number")
h2_eff_channel_onlyNumerator.GetYaxis().SetTitleOffset(0.9)
h2_eff_channel_onlyNumerator.GetYaxis().SetTitleSize(0.04)
h2_eff_channel_onlyNumerator.GetZaxis().SetTitle("Hits")
h2_eff_channel_onlyNumerator.GetZaxis().SetTitleOffset(1.3)
h2_eff_channel_onlyNumerator.Draw("COLZ0")
myc.Update()
myc.SaveAs("effplots/h2_eff_channel_onlyNumerator.eps")
myc.SaveAs("effplots/h2_eff_channel_onlyNumerator.png")
myc.Close()


'''
myc= ROOT.TCanvas("myc", "myc", 800, 600)
myc.SetMargin(0.12,0.05,0.1,0.05)
h_qsum.SetStats(ROOT.kFALSE)
h_qsum.SetTitle("")
h_qsum.GetXaxis().SetTitle("qsum")
h_qsum.GetYaxis().SetTitle("Number of hits")
h_qsum.GetYaxis().SetTitleOffset(1.4)
h_qsum.GetYaxis().SetTitleSize(0.04)
h_qsum.Draw()
myc.Update()
myc.SaveAs("effplots/h_qsum.eps")
myc.SaveAs("effplots/h_qsum.png")
myc.Close()
'''


